import type { Invoice } from '../types/finance';

export const INVOICES: Invoice[] = [
  {
    id: 'INV-5001',
    invoiceNo: 'INV-RIL-70112',
    vendor: 'Larsen & Toubro',
    orderId: 'ORD-2041',
    plant: 'Jamnagar',
    amountCr: 3.8,
    dueDate: '2026-08-14',
    invoiceStatus: 'Matched',
    paymentStatus: 'Scheduled',
    scfStatus: 'Eligible',
  },
  {
    id: 'INV-5002',
    invoiceNo: 'INV-RIL-70118',
    vendor: 'Praj Industries',
    orderId: 'ORD-2042',
    plant: 'Delhi',
    amountCr: 1.2,
    dueDate: '2026-07-28',
    invoiceStatus: 'Mismatch',
    paymentStatus: 'Overdue',
    scfStatus: 'Not Eligible',
  },
  {
    id: 'INV-5003',
    invoiceNo: 'INV-RIL-70125',
    vendor: 'Thermax Ltd',
    orderId: 'ORD-2043',
    plant: 'Hyderabad',
    amountCr: 2.6,
    dueDate: '2026-09-02',
    invoiceStatus: 'Submitted',
    paymentStatus: 'Pending',
    scfStatus: 'Eligible',
  },
  {
    id: 'INV-5004',
    invoiceNo: 'INV-RIL-70131',
    vendor: 'Kirloskar Brothers',
    orderId: 'ORD-2044',
    plant: 'Nagpur',
    amountCr: 0.9,
    dueDate: '2026-08-20',
    invoiceStatus: 'Approved',
    paymentStatus: 'Released',
    scfStatus: 'Discounted',
  },
  {
    id: 'INV-5005',
    invoiceNo: 'INV-RIL-70140',
    vendor: 'TEMA India',
    orderId: 'ORD-2045',
    plant: 'Jamnagar',
    amountCr: 4.4,
    dueDate: '2026-08-09',
    invoiceStatus: 'Matched',
    paymentStatus: 'Pending',
    scfStatus: 'Eligible',
  },
  {
    id: 'INV-5006',
    invoiceNo: 'INV-RIL-70148',
    vendor: 'Larsen & Toubro',
    orderId: 'ORD-2049',
    plant: 'Surat',
    amountCr: 1.7,
    dueDate: '2026-07-25',
    invoiceStatus: 'Approved',
    paymentStatus: 'Paid',
    scfStatus: 'Not Eligible',
  },
  {
    id: 'INV-5007',
    invoiceNo: 'INV-RIL-70153',
    vendor: 'Thermax Ltd',
    orderId: 'ORD-2052',
    plant: 'Delhi',
    amountCr: 2.1,
    dueDate: '2026-08-31',
    invoiceStatus: 'Submitted',
    paymentStatus: 'Pending',
    scfStatus: 'Eligible',
  },
  {
    id: 'INV-5008',
    invoiceNo: 'INV-RIL-70161',
    vendor: 'Praj Industries',
    orderId: 'ORD-2055',
    plant: 'Hyderabad',
    amountCr: 0.6,
    dueDate: '2026-08-02',
    invoiceStatus: 'Rejected',
    paymentStatus: 'Pending',
    scfStatus: 'Not Eligible',
  },
  {
    id: 'INV-5009',
    invoiceNo: 'INV-RIL-70166',
    vendor: 'Kirloskar Brothers',
    orderId: 'ORD-2058',
    plant: 'Nagpur',
    amountCr: 3.2,
    dueDate: '2026-09-11',
    invoiceStatus: 'Matched',
    paymentStatus: 'Scheduled',
    scfStatus: 'Discounted',
  },
  {
    id: 'INV-5010',
    invoiceNo: 'INV-RIL-70172',
    vendor: 'TEMA India',
    orderId: 'ORD-2061',
    plant: 'Surat',
    amountCr: 1.4,
    dueDate: '2026-08-18',
    invoiceStatus: 'Approved',
    paymentStatus: 'Released',
    scfStatus: 'Eligible',
  },
  {
    id: 'INV-5011',
    invoiceNo: 'INV-RIL-70180',
    vendor: 'Larsen & Toubro',
    orderId: 'ORD-2064',
    plant: 'Jamnagar',
    amountCr: 5.6,
    dueDate: '2026-09-20',
    invoiceStatus: 'Submitted',
    paymentStatus: 'Pending',
    scfStatus: 'Eligible',
  },
];

export const INVOICE_VENDORS = [...new Set(INVOICES.map((invoice) => invoice.vendor))].sort();
