import type {
  Opportunity,
  OpportunityDepartment,
  OpportunityImpact,
  OpportunityPriority,
  OpportunityStatus,
} from '../types/insights';

export const OPPORTUNITY_DEPARTMENTS: OpportunityDepartment[] = [
  'Procurement',
  'Site Operations',
  'Quality',
  'Finance',
  'Security',
  'Governance',
];

export const OPPORTUNITY_PRIORITIES: OpportunityPriority[] = ['Critical', 'High', 'Medium', 'Low'];

export const OPPORTUNITY_STATUSES: OpportunityStatus[] = [
  'Backlog',
  'In Progress',
  'In Review',
  'Completed',
  'On Hold',
];

export const OPPORTUNITY_IMPACTS: OpportunityImpact[] = ['High', 'Medium', 'Low'];

export const OPPORTUNITY_OWNERS = [
  'Rakesh Sharma',
  'Anita Desai',
  'Vikram Nair',
  'Priya Menon',
  'Sanjay Iyer',
  'Neha Kulkarni',
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'DIG-301',
    title: 'Digitize gate pass issuance at plant entry',
    department: 'Security',
    priority: 'Critical',
    owner: 'Sanjay Iyer',
    status: 'In Progress',
    impact: 'High',
    lastUpdated: '2026-07-28',
  },
  {
    id: 'DIG-302',
    title: 'Replace manual weighment slips with digital capture',
    department: 'Site Operations',
    priority: 'High',
    owner: 'Vikram Nair',
    status: 'In Progress',
    impact: 'High',
    lastUpdated: '2026-07-24',
  },
  {
    id: 'DIG-303',
    title: 'Automate three-way invoice matching',
    department: 'Finance',
    priority: 'High',
    owner: 'Priya Menon',
    status: 'In Review',
    impact: 'High',
    lastUpdated: '2026-07-21',
  },
  {
    id: 'DIG-304',
    title: 'Standardise QC inspection checklists across contract types',
    department: 'Quality',
    priority: 'High',
    owner: 'Anita Desai',
    status: 'Backlog',
    impact: 'High',
    lastUpdated: '2026-07-18',
  },
  {
    id: 'DIG-305',
    title: 'Auto-escalate governance approvals past SLA',
    department: 'Governance',
    priority: 'Critical',
    owner: 'Rakesh Sharma',
    status: 'In Progress',
    impact: 'High',
    lastUpdated: '2026-07-30',
  },
  {
    id: 'DIG-306',
    title: 'Central compliance document library with expiry alerts',
    department: 'Governance',
    priority: 'Medium',
    owner: 'Neha Kulkarni',
    status: 'Backlog',
    impact: 'Medium',
    lastUpdated: '2026-07-12',
  },
  {
    id: 'DIG-307',
    title: 'Vendor manpower roster upload instead of register books',
    department: 'Site Operations',
    priority: 'Medium',
    owner: 'Vikram Nair',
    status: 'On Hold',
    impact: 'Medium',
    lastUpdated: '2026-06-30',
  },
  {
    id: 'DIG-308',
    title: 'Digital acknowledgement of proof of delivery',
    department: 'Procurement',
    priority: 'Medium',
    owner: 'Priya Menon',
    status: 'In Review',
    impact: 'Medium',
    lastUpdated: '2026-07-16',
  },
  {
    id: 'DIG-309',
    title: 'Vendor KYC document renewal reminders',
    department: 'Procurement',
    priority: 'Low',
    owner: 'Neha Kulkarni',
    status: 'Backlog',
    impact: 'Low',
    lastUpdated: '2026-07-05',
  },
  {
    id: 'DIG-310',
    title: 'Structured damage and shortage reporting at gate-in',
    department: 'Quality',
    priority: 'High',
    owner: 'Anita Desai',
    status: 'Completed',
    impact: 'High',
    lastUpdated: '2026-06-24',
  },
  {
    id: 'DIG-311',
    title: 'SCF eligibility visibility at milestone closure',
    department: 'Finance',
    priority: 'High',
    owner: 'Priya Menon',
    status: 'Completed',
    impact: 'High',
    lastUpdated: '2026-06-18',
  },
  {
    id: 'DIG-312',
    title: 'Single audit trail across order and vendor actions',
    department: 'Governance',
    priority: 'Medium',
    owner: 'Rakesh Sharma',
    status: 'In Progress',
    impact: 'Medium',
    lastUpdated: '2026-07-26',
  },
  {
    id: 'DIG-313',
    title: 'Security pass validity check at the gate terminal',
    department: 'Security',
    priority: 'High',
    owner: 'Sanjay Iyer',
    status: 'In Review',
    impact: 'High',
    lastUpdated: '2026-07-20',
  },
  {
    id: 'DIG-314',
    title: 'Retire spreadsheet tracking of dispatch schedules',
    department: 'Procurement',
    priority: 'Low',
    owner: 'Vikram Nair',
    status: 'On Hold',
    impact: 'Low',
    lastUpdated: '2026-06-12',
  },
  {
    id: 'DIG-315',
    title: 'Stakeholder reassignment without offline approval mails',
    department: 'Governance',
    priority: 'Low',
    owner: 'Neha Kulkarni',
    status: 'Backlog',
    impact: 'Medium',
    lastUpdated: '2026-07-08',
  },
];
