import type { Gate, Order } from '../types/order';

export const TODAY = new Date('2026-07-30T00:00:00');

const GATE_CHAIN: { key: string; label: string }[] = [
  { key: 'clearance', label: 'Security Clearance' },
  { key: 'documents', label: 'Document Verification' },
  { key: 'gate-in', label: 'Material Gate-In' },
  { key: 'qc', label: 'QC Inspection' },
  { key: 'delivery', label: 'Delivery Confirmation' },
  { key: 'governance', label: 'Governance Approval' },
  { key: 'payment', label: 'Payment Release' },
];

function gates(currentIndex: number): Gate[] {
  return GATE_CHAIN.map((gate, index) => ({
    ...gate,
    state: index < currentIndex ? 'done' : index === currentIndex ? 'current' : 'locked',
  }));
}

export const ORDERS: Order[] = [
  {
    id: 'ORD-2041',
    po: 'PO-RIL-88213',
    vendor: 'Larsen & Toubro',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'In QC',
    progress: 62,
    expected: '2026-08-14',
    valueCr: 3.8,
    gates: gates(3),
    flags: [],
  },
  {
    id: 'ORD-2042',
    po: 'PO-RIL-88240',
    vendor: 'Praj Industries',
    plant: 'Delhi',
    type: 'Material',
    status: 'Delayed',
    progress: 45,
    expected: '2026-08-05',
    valueCr: 1.2,
    gates: gates(2),
    flags: [{ type: 'delayed', detail: 'Carrier reported a 4-day transit delay at Delhi.' }],
  },
  {
    id: 'ORD-2043',
    po: 'PO-RIL-88255',
    vendor: 'Thermax Ltd',
    plant: 'Hyderabad',
    type: 'Manufactured',
    status: 'Gate-In',
    progress: 30,
    expected: '2026-09-02',
    valueCr: 2.6,
    gates: gates(2),
    flags: [],
  },
  {
    id: 'ORD-2044',
    po: 'PO-RIL-88261',
    vendor: 'Kirloskar Brothers',
    plant: 'Nagpur',
    type: 'Material',
    status: 'Partially Delivered',
    progress: 70,
    expected: '2026-08-20',
    valueCr: 0.9,
    gates: gates(4),
    flags: [{ type: 'partial', detail: '18 of 24 line items received; balance scheduled.' }],
  },
  {
    id: 'ORD-2045',
    po: 'PO-RIL-88277',
    vendor: 'TEMA India',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'Blocked - Governance',
    progress: 55,
    expected: '2026-08-28',
    valueCr: 4.5,
    gates: gates(5),
    flags: [{ type: 'blocked', detail: 'Governance sign-off pending on QC waiver.' }],
  },
  {
    id: 'ORD-2046',
    po: 'PO-RIL-88290',
    vendor: 'ISGEC Heavy Engineering',
    plant: 'Surat',
    type: 'Manufactured',
    status: 'Delivered',
    progress: 100,
    expected: '2026-07-18',
    valueCr: 5.1,
    gates: gates(7),
    flags: [],
  },
  {
    id: 'ORD-2047',
    po: 'PO-RIL-88302',
    vendor: 'Supreme Petrochem',
    plant: 'Delhi',
    type: 'Material',
    status: 'Damaged Items Reported',
    progress: 60,
    expected: '2026-08-11',
    valueCr: 0.7,
    gates: gates(3),
    flags: [
      { type: 'damaged', detail: '4 units damaged in transit; QC rejection raised.' },
      { type: 'missing', detail: '8 units short against the dispatch note.' },
    ],
  },
  {
    id: 'ORD-2048',
    po: 'PO-RIL-88318',
    vendor: 'Bharat Heavy Electricals',
    plant: 'Hyderabad',
    type: 'Manufactured',
    status: 'Awaiting Security Clearance',
    progress: 10,
    expected: '2026-09-15',
    valueCr: 6.3,
    gates: gates(0),
    flags: [],
  },
  {
    id: 'ORD-2049',
    po: 'PO-RIL-88331',
    vendor: 'Larsen & Toubro',
    plant: 'Hyderabad',
    type: 'Manufactured',
    status: 'In QC',
    progress: 58,
    expected: '2026-08-22',
    valueCr: 4.2,
    gates: gates(3),
    flags: [],
  },
  {
    id: 'ORD-2050',
    po: 'PO-RIL-88347',
    vendor: 'Kirloskar Brothers',
    plant: 'Jamnagar',
    type: 'Material',
    status: 'In Transit',
    progress: 38,
    expected: '2026-08-18',
    valueCr: 1.4,
    gates: gates(2),
    flags: [],
  },
  {
    id: 'ORD-2051',
    po: 'PO-RIL-88352',
    vendor: 'Thermax Ltd',
    plant: 'Delhi',
    type: 'Material',
    status: 'Delayed',
    progress: 33,
    expected: '2026-08-07',
    valueCr: 0.8,
    gates: gates(2),
    flags: [{ type: 'delayed', detail: 'Vendor dispatch slipped by 6 days.' }],
  },
  {
    id: 'ORD-2052',
    po: 'PO-RIL-88364',
    vendor: 'ISGEC Heavy Engineering',
    plant: 'Surat',
    type: 'Manufactured',
    status: 'Awaiting Documents',
    progress: 18,
    expected: '2026-09-06',
    valueCr: 2.9,
    gates: gates(1),
    flags: [{ type: 'blocked', detail: 'Missing labor license before document verification can close.' }],
  },
  {
    id: 'ORD-2053',
    po: 'PO-RIL-88372',
    vendor: 'Supreme Petrochem',
    plant: 'Nagpur',
    type: 'Material',
    status: 'Document Verification',
    progress: 24,
    expected: '2026-08-26',
    valueCr: 1.1,
    gates: gates(1),
    flags: [],
  },
  {
    id: 'ORD-2054',
    po: 'PO-RIL-88386',
    vendor: 'Praj Industries',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'Waiting for Security Clearance',
    progress: 8,
    expected: '2026-09-20',
    valueCr: 3.2,
    gates: gates(0),
    flags: [],
  },
  {
    id: 'ORD-2055',
    po: 'PO-RIL-88395',
    vendor: 'TEMA India',
    plant: 'Delhi',
    type: 'Manufactured',
    status: 'Blocked - Security',
    progress: 5,
    expected: '2026-09-18',
    valueCr: 4.9,
    gates: gates(0),
    flags: [{ type: 'blocked', detail: 'Personnel pass renewal pending with security desk.' }],
  },
  {
    id: 'ORD-2056',
    po: 'PO-RIL-88406',
    vendor: 'Bharat Heavy Electricals',
    plant: 'Surat',
    type: 'Manufactured',
    status: 'Delivery Confirmation',
    progress: 78,
    expected: '2026-08-09',
    valueCr: 6.8,
    gates: gates(4),
    flags: [],
  },
  {
    id: 'ORD-2057',
    po: 'PO-RIL-88411',
    vendor: 'Larsen & Toubro',
    plant: 'Nagpur',
    type: 'Manufactured',
    status: 'Delayed',
    progress: 76,
    expected: '2026-08-03',
    valueCr: 2.2,
    gates: gates(4),
    flags: [{ type: 'delayed', detail: 'Proof of delivery not received from site lead.' }],
  },
  {
    id: 'ORD-2058',
    po: 'PO-RIL-88424',
    vendor: 'Kirloskar Brothers',
    plant: 'Hyderabad',
    type: 'Material',
    status: 'Governance Review',
    progress: 84,
    expected: '2026-08-12',
    valueCr: 1.7,
    gates: gates(5),
    flags: [],
  },
  {
    id: 'ORD-2059',
    po: 'PO-RIL-88438',
    vendor: 'Thermax Ltd',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'Payment Scheduled',
    progress: 92,
    expected: '2026-08-16',
    valueCr: 3.5,
    gates: gates(6),
    flags: [],
  },
  {
    id: 'ORD-2060',
    po: 'PO-RIL-88447',
    vendor: 'Supreme Petrochem',
    plant: 'Delhi',
    type: 'Material',
    status: 'Payment On Hold',
    progress: 88,
    expected: '2026-08-06',
    valueCr: 0.6,
    gates: gates(6),
    flags: [{ type: 'blocked', detail: 'Invoice mismatch holds payment release.' }],
  },
  {
    id: 'ORD-2061',
    po: 'PO-RIL-88453',
    vendor: 'Praj Industries',
    plant: 'Hyderabad',
    type: 'Material',
    status: 'Completed',
    progress: 100,
    expected: '2026-07-30',
    valueCr: 1.9,
    gates: gates(7),
    flags: [],
  },
  {
    id: 'ORD-2062',
    po: 'PO-RIL-88468',
    vendor: 'TEMA India',
    plant: 'Surat',
    type: 'Manufactured',
    status: 'Material Gate-In',
    progress: 41,
    expected: '2026-08-24',
    valueCr: 5.6,
    gates: gates(2),
    flags: [],
  },
  {
    id: 'ORD-2063',
    po: 'PO-RIL-88479',
    vendor: 'Bharat Heavy Electricals',
    plant: 'Nagpur',
    type: 'Manufactured',
    status: 'Waiting for Previous Gate',
    progress: 26,
    expected: '2026-09-01',
    valueCr: 4.1,
    gates: gates(1),
    flags: [{ type: 'blocked', detail: 'Previous gate incomplete: security document exception remains open.' }],
  },
  {
    id: 'ORD-2064',
    po: 'PO-RIL-88485',
    vendor: 'ISGEC Heavy Engineering',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'Governance Escalated',
    progress: 82,
    expected: '2026-08-02',
    valueCr: 7.4,
    gates: gates(5),
    flags: [{ type: 'blocked', detail: 'Board-level approval required for value threshold exception.' }],
  },
  {
    id: 'ORD-2065',
    po: 'PO-RIL-88491',
    vendor: 'Godrej Process Equipment',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'In QC',
    progress: 64,
    expected: '2026-08-19',
    valueCr: 3.1,
    gates: gates(3),
    flags: [],
  },
  {
    id: 'ORD-2066',
    po: 'PO-RIL-88497',
    vendor: 'Godrej Process Equipment',
    plant: 'Hyderabad',
    type: 'Material',
    status: 'Payment Scheduled',
    progress: 90,
    expected: '2026-08-13',
    valueCr: 1.3,
    gates: gates(6),
    flags: [],
  },
  {
    id: 'ORD-2067',
    po: 'PO-RIL-88503',
    vendor: 'Alfa Laval India',
    plant: 'Delhi',
    type: 'Manufactured',
    status: 'Delivery Confirmation',
    progress: 74,
    expected: '2026-08-10',
    valueCr: 2.4,
    gates: gates(4),
    flags: [],
  },
  {
    id: 'ORD-2068',
    po: 'PO-RIL-88509',
    vendor: 'Alfa Laval India',
    plant: 'Surat',
    type: 'Material',
    status: 'Completed',
    progress: 100,
    expected: '2026-07-21',
    valueCr: 0.8,
    gates: gates(7),
    flags: [],
  },
  {
    id: 'ORD-2069',
    po: 'PO-RIL-88514',
    vendor: 'Grasim Industries',
    plant: 'Nagpur',
    type: 'Material',
    status: 'Material Gate-In',
    progress: 36,
    expected: '2026-08-27',
    valueCr: 1.6,
    gates: gates(2),
    flags: [],
  },
  {
    id: 'ORD-2070',
    po: 'PO-RIL-88521',
    vendor: 'Grasim Industries',
    plant: 'Jamnagar',
    type: 'Material',
    status: 'Delayed',
    progress: 48,
    expected: '2026-08-04',
    valueCr: 2.1,
    gates: gates(3),
    flags: [{ type: 'delayed', detail: 'Tanker fleet held for hazardous clearance at Jamnagar.' }],
  },
  {
    id: 'ORD-2071',
    po: 'PO-RIL-88528',
    vendor: 'Sud-Chemie Catalysts',
    plant: 'Jamnagar',
    type: 'Material',
    status: 'Governance Review',
    progress: 83,
    expected: '2026-08-15',
    valueCr: 4.6,
    gates: gates(5),
    flags: [],
  },
  {
    id: 'ORD-2072',
    po: 'PO-RIL-88534',
    vendor: 'Sud-Chemie Catalysts',
    plant: 'Jamnagar',
    type: 'Material',
    status: 'Awaiting Documents',
    progress: 20,
    expected: '2026-09-08',
    valueCr: 3.4,
    gates: gates(1),
    flags: [{ type: 'blocked', detail: 'Catalyst handling certificate expiring before dispatch.' }],
  },
  {
    id: 'ORD-2073',
    po: 'PO-RIL-88540',
    vendor: 'Emerson Automation',
    plant: 'Hyderabad',
    type: 'Manufactured',
    status: 'In QC',
    progress: 57,
    expected: '2026-08-21',
    valueCr: 2.8,
    gates: gates(3),
    flags: [],
  },
  {
    id: 'ORD-2074',
    po: 'PO-RIL-88546',
    vendor: 'Emerson Automation',
    plant: 'Delhi',
    type: 'Material',
    status: 'Delivered',
    progress: 100,
    expected: '2026-07-24',
    valueCr: 1.1,
    gates: gates(7),
    flags: [],
  },
  {
    id: 'ORD-2075',
    po: 'PO-RIL-88552',
    vendor: 'Yokogawa India',
    plant: 'Surat',
    type: 'Manufactured',
    status: 'Document Verification',
    progress: 22,
    expected: '2026-09-04',
    valueCr: 2.3,
    gates: gates(1),
    flags: [],
  },
  {
    id: 'ORD-2076',
    po: 'PO-RIL-88558',
    vendor: 'Yokogawa India',
    plant: 'Surat',
    type: 'Material',
    status: 'Awaiting Security Clearance',
    progress: 9,
    expected: '2026-09-16',
    valueCr: 0.9,
    gates: gates(0),
    flags: [],
  },
  {
    id: 'ORD-2077',
    po: 'PO-RIL-88563',
    vendor: 'Simplex Infrastructures',
    plant: 'Nagpur',
    type: 'Manufactured',
    status: 'Blocked - Security',
    progress: 12,
    expected: '2026-09-11',
    valueCr: 3.9,
    gates: gates(0),
    flags: [{ type: 'blocked', detail: 'Labour induction records expired for the site crew.' }],
  },
  {
    id: 'ORD-2078',
    po: 'PO-RIL-88569',
    vendor: 'Simplex Infrastructures',
    plant: 'Delhi',
    type: 'Material',
    status: 'Delayed',
    progress: 40,
    expected: '2026-08-01',
    valueCr: 1.5,
    gates: gates(2),
    flags: [{ type: 'delayed', detail: 'Structural steel dispatch slipped by 9 days.' }],
  },
  {
    id: 'ORD-2079',
    po: 'PO-RIL-88575',
    vendor: 'Uflex Packaging',
    plant: 'Hyderabad',
    type: 'Material',
    status: 'Partially Delivered',
    progress: 68,
    expected: '2026-08-17',
    valueCr: 0.7,
    gates: gates(4),
    flags: [{ type: 'partial', detail: '32 of 48 pallets received; balance in transit.' }],
  },
  {
    id: 'ORD-2080',
    po: 'PO-RIL-88581',
    vendor: 'Uflex Packaging',
    plant: 'Delhi',
    type: 'Material',
    status: 'Completed',
    progress: 100,
    expected: '2026-07-19',
    valueCr: 0.5,
    gates: gates(7),
    flags: [],
  },
  {
    id: 'ORD-2081',
    po: 'PO-RIL-88587',
    vendor: 'Allcargo Logistics',
    plant: 'Jamnagar',
    type: 'Material',
    status: 'In Transit',
    progress: 34,
    expected: '2026-08-23',
    valueCr: 1.2,
    gates: gates(2),
    flags: [],
  },
  {
    id: 'ORD-2082',
    po: 'PO-RIL-88593',
    vendor: 'Allcargo Logistics',
    plant: 'Surat',
    type: 'Material',
    status: 'Payment On Hold',
    progress: 87,
    expected: '2026-08-08',
    valueCr: 0.6,
    gates: gates(6),
    flags: [{ type: 'blocked', detail: 'Freight invoice mismatch against the delivery note.' }],
  },
  {
    id: 'ORD-2083',
    po: 'PO-RIL-88599',
    vendor: 'Flowserve India',
    plant: 'Jamnagar',
    type: 'Manufactured',
    status: 'Blocked - Governance',
    progress: 59,
    expected: '2026-08-25',
    valueCr: 5.4,
    gates: gates(5),
    flags: [{ type: 'blocked', detail: 'Vendor KYC incomplete for a value above the release threshold.' }],
  },
  {
    id: 'ORD-2084',
    po: 'PO-RIL-88605',
    vendor: 'Flowserve India',
    plant: 'Surat',
    type: 'Material',
    status: 'Damaged Items Reported',
    progress: 52,
    expected: '2026-08-12',
    valueCr: 1.8,
    gates: gates(3),
    flags: [{ type: 'damaged', detail: '3 mechanical seals damaged in transit; QC rejection raised.' }],
  },
  {
    id: 'ORD-2085',
    po: 'PO-RIL-88611',
    vendor: 'Siemens Energy India',
    plant: 'Hyderabad',
    type: 'Manufactured',
    status: 'Governance Review',
    progress: 81,
    expected: '2026-08-14',
    valueCr: 6.1,
    gates: gates(5),
    flags: [],
  },
  {
    id: 'ORD-2086',
    po: 'PO-RIL-88617',
    vendor: 'Siemens Energy India',
    plant: 'Nagpur',
    type: 'Manufactured',
    status: 'Waiting for Previous Gate',
    progress: 28,
    expected: '2026-09-03',
    valueCr: 4.4,
    gates: gates(1),
    flags: [],
  },
  {
    id: 'ORD-2087',
    po: 'PO-RIL-88623',
    vendor: 'Tata Projects',
    plant: 'Surat',
    type: 'Manufactured',
    status: 'Delivery Confirmation',
    progress: 77,
    expected: '2026-08-11',
    valueCr: 5.8,
    gates: gates(4),
    flags: [],
  },
  {
    id: 'ORD-2088',
    po: 'PO-RIL-88629',
    vendor: 'Tata Projects',
    plant: 'Delhi',
    type: 'Manufactured',
    status: 'In QC',
    progress: 61,
    expected: '2026-08-29',
    valueCr: 3.6,
    gates: gates(3),
    flags: [],
  },
];

export const ORDER_PLANTS = ['Jamnagar', 'Delhi', 'Hyderabad', 'Nagpur', 'Surat'] as const;
