

import type { Gate, Order } from '../types/order';


export const TODAY = new Date('2026-07-30T00:00:00');

const GATE_CHAIN: { key: string; label: string }[] = [
  { key: 'clearance', label: 'Security Clearance' },
  { key: 'documents', label: 'Doc Verification' },
  { key: 'gate-in', label: 'Gate-In' },
  { key: 'qc', label: 'QC' },
  { key: 'delivery', label: 'Delivery' },
  { key: 'governance', label: 'Governance' },
  { key: 'payment', label: 'Payment' },
];

function gates(currentIndex: number): Gate[] {
  return GATE_CHAIN.map((gate, i) => ({
    ...gate,
    state: i < currentIndex ? 'done' : i === currentIndex ? 'current' : 'locked',
  }));
}

export const ORDERS: Order[] = [
  // {
  //   id: 'ORD-2041',
  //   po: 'PO-RIL-88213',
  //   vendor: 'Larsen & Toubro',
  //   plant: 'Jamnagar',
  //   type: 'Manufactured',
  //   status: 'In QC',
  //   progress: 62,
  //   expected: '2026-08-14',
  //   valueCr: 3.8,
  //   gates: gates(3),
  //   flags: [],
  // },
  // {
  //   id: 'ORD-2042',
  //   po: 'PO-RIL-88240',
  //   vendor: 'Praj Industries',
  //   plant: 'Dahej',
  //   type: 'Material',
  //   status: 'Delayed',
  //   progress: 45,
  //   expected: '2026-08-05',
  //   valueCr: 1.2,
  //   gates: gates(2),
  //   flags: [{ type: 'delayed', detail: 'Carrier reported a 4-day transit delay at Dahej.' }],
  // },
  // {
  //   id: 'ORD-2043',
  //   po: 'PO-RIL-88255',
  //   vendor: 'Thermax Ltd',
  //   plant: 'Hazira',
  //   type: 'Manufactured',
  //   status: 'Gate-In',
  //   progress: 30,
  //   expected: '2026-09-02',
  //   valueCr: 2.6,
  //   gates: gates(2),
  //   flags: [],
  // },
  // {
  //   id: 'ORD-2044',
  //   po: 'PO-RIL-88261',
  //   vendor: 'Kirloskar Brothers',
  //   plant: 'Nagothane',
  //   type: 'Material',
  //   status: 'Partially Delivered',
  //   progress: 70,
  //   expected: '2026-08-20',
  //   valueCr: 0.9,
  //   gates: gates(3),
  //   flags: [{ type: 'partial', detail: '18 of 24 line items received; balance scheduled.' }],
  // },
  // {
  //   id: 'ORD-2045',
  //   po: 'PO-RIL-88277',
  //   vendor: 'TEMA India',
  //   plant: 'Jamnagar',
  //   type: 'Manufactured',
  //   status: 'Blocked – Governance',
  //   progress: 55,
  //   expected: '2026-08-28',
  //   valueCr: 4.5,
  //   gates: gates(5),
  //   flags: [{ type: 'blocked', detail: 'Governance sign-off pending — hard dependency on QC waiver.' }],
  // },
  // {
  //   id: 'ORD-2046',
  //   po: 'PO-RIL-88290',
  //   vendor: 'ISGEC Heavy Engineering',
  //   plant: 'Silvassa',
  //   type: 'Manufactured',
  //   status: 'Delivered',
  //   progress: 100,
  //   expected: '2026-07-18',
  //   valueCr: 5.1,
  //   gates: gates(7),
  //   flags: [],
  // },
  // {
  //   id: 'ORD-2047',
  //   po: 'PO-RIL-88302',
  //   vendor: 'Supreme Petrochem',
  //   plant: 'Dahej',
  //   type: 'Material',
  //   status: 'Damaged Items Reported',
  //   progress: 60,
  //   expected: '2026-08-11',
  //   valueCr: 0.7,
  //   gates: gates(3),
  //   flags: [
  //     { type: 'damaged', detail: '4 units damaged in transit — QC rejection raised.' },
  //     { type: 'missing', detail: '8 units short against the dispatch note.' },
  //   ],
  // },
  // {
  //   id: 'ORD-2048',
  //   po: 'PO-RIL-88318',
  //   vendor: 'Bharat Heavy Electricals',
  //   plant: 'Hazira',
  //   type: 'Manufactured',
  //   status: 'Awaiting Security Clearance',
  //   progress: 10,
  //   expected: '2026-09-15',
  //   valueCr: 6.3,
  //   gates: gates(0),
  //   flags: [],
  // },
  // {
  //   id: 'ORD-2049',
  //   po: 'PO-RIL-88331',
  //   vendor: 'Larsen & Toubro',
  //   plant: 'Hazira',
  //   type: 'Manufactured',
  //   status: 'In QC',
  //   progress: 58,
  //   expected: '2026-08-22',
  //   valueCr: 4.2,
  //   gates: gates(3),
  //   flags: [],
  // },
  // {
  //   id: 'ORD-2050',
  //   po: 'PO-RIL-88347',
  //   vendor: 'Kirloskar Brothers',
  //   plant: 'Jamnagar',
  //   type: 'Material',
  //   status: 'In Transit',
  //   progress: 38,
  //   expected: '2026-08-18',
  //   valueCr: 1.4,
  //   gates: gates(2),
  //   flags: [],
  // },
  // {
  //   id: 'ORD-2051',
  //   po: 'PO-RIL-88352',
  //   vendor: 'Thermax Ltd',
  //   plant: 'Dahej',
  //   type: 'Material',
  //   status: 'Delayed',
  //   progress: 33,
  //   expected: '2026-08-07',
  //   valueCr: 0.8,
  //   gates: gates(2),
  //   flags: [{ type: 'delayed', detail: 'Vendor dispatch slipped by 6 days.' }],
  // },
];

export const ORDER_PLANTS = ['Jamnagar', 'Dahej', 'Hazira', 'Nagothane', 'Silvassa'] as const;
