import type { ActivityEntry, AttachedDocument } from '../types/orderDetail';
import type {
  JourneyStage,
  ManpowerRecord,
  Movement,
  MovementDirection,
  MovementStatus,
} from '../types/siteOps';

/** The plant clock the demo calendar is frozen at — dwell and delay derive from it. */
export const SITE_CLOCK = new Date('2026-07-30T13:20:00');

const DAY = '2026-07-30';

function at(time: string): string {
  return `${DAY}T${time}:00`;
}

export const GATES = ['Gate 1', 'Gate 2', 'Gate 3', 'Gate 4', 'Project Gate', 'Hazardous Material Gate'];

export const VEHICLE_TYPES = ['Trailer', 'Container Truck', 'Flatbed', 'Tanker', 'LCV'];

export const SITE_ZONES = [
  'Entry Lane 1',
  'Entry Lane 2',
  'Security Hold Yard',
  'Weighbridge 1',
  'Weighbridge 2',
  'QC Bay 1',
  'QC Hold Area',
  'Unloading Bay 3',
  'Loading Bay 2',
  'Exit Lane 1',
];

const INBOUND_CHAIN = [
  { key: 'entry', label: 'Entry' },
  { key: 'security', label: 'Security' },
  { key: 'weighment', label: 'Weighment' },
  { key: 'qc', label: 'QC' },
  { key: 'unloading', label: 'Unloading' },
  { key: 'exit', label: 'Exit' },
];

const OUTBOUND_CHAIN = [
  { key: 'entry', label: 'Entry' },
  { key: 'security', label: 'Security' },
  { key: 'loading', label: 'Loading' },
  { key: 'weighment', label: 'Weighment' },
  { key: 'exit', label: 'Exit' },
];

export function journeyChain(direction: MovementDirection) {
  return direction === 'Gate-In' ? INBOUND_CHAIN : OUTBOUND_CHAIN;
}

/**
 * One journey builder for every movement — the rail state is derived from the
 * index the vehicle has reached, never authored node by node.
 */
export function buildJourney(
  direction: MovementDirection,
  currentIndex: number,
  mark: 'none' | 'blocked' | 'delayed' = 'none',
  times: Record<string, string> = {},
): JourneyStage[] {
  const chain = journeyChain(direction);

  return chain.map((stage, index) => {
    const state: JourneyStage['state'] =
      index < currentIndex
        ? 'complete'
        : index > currentIndex
          ? 'upcoming'
          : mark === 'blocked'
            ? 'blocked'
            : mark === 'delayed'
              ? 'delayed'
              : 'current';

    return { ...stage, state, at: times[stage.key] };
  });
}

function docs(entries: [string, string, string][]): AttachedDocument[] {
  return entries.map(([name, type, status], index) => ({
    id: `${name.toLowerCase().replace(/\s+/g, '-')}-${index}`,
    name,
    type,
    status,
    uploadedBy: 'Gate Desk',
    uploadedAt: '30 Jul 2026',
  }));
}

function log(id: string, entries: [string, string, string][]): ActivityEntry[] {
  return entries.map(([actor, action, time], index) => ({
    id: `${id}-act-${index + 1}`,
    actor,
    action,
    timestamp: at(time),
    type: 'delivery',
  }));
}

export const MOVEMENTS: Movement[] = [
  {
    id: 'GT-4103',
    direction: 'Gate-In',
    vehicle: 'GJ-05-BB-3312',
    vehicleType: 'Trailer',
    driver: 'Suresh Yadav',
    driverContact: '+91 98204 41120',
    transporter: 'Gati',
    vendor: 'TEMA India',
    orderId: 'ORD-2055',
    plant: 'Delhi',
    gate: 'Project Gate',
    zone: 'Security Hold Yard',
    material: 'Heat exchanger bundles',
    status: 'Blocked',
    entryAt: at('09:05'),
    expectedExit: at('12:00'),
    exitAt: null,
    pass: { id: 'SP-2214', holder: 'Suresh Yadav', validTo: '2026-07-29', status: 'Expired' },
    weighment: { grossKg: null, tareKg: null },
    labourIn: 4,
    labourOut: 0,
    remarks: 'Held at the security yard pending pass renewal.',
    photos: ['Vehicle front', 'Driver ID'],
    documents: docs([
      ['Gate Pass Request', 'Gate Pass', 'Pending'],
      ['Driver ID Proof', 'ID Proof', 'Submitted'],
    ]),
    activity: log('GT-4103', [
      ['Amit Kulkarni', 'flagged the security pass as expired at the project gate', '09:18'],
      ['Gate Desk', 'recorded arrival at Project Gate', '09:05'],
    ]),
    stages: buildJourney('Gate-In', 1, 'blocked', { entry: at('09:05') }),
    blockedReason: 'Personnel pass renewal pending with the security desk.',
  },
  {
    id: 'GT-4105',
    direction: 'Gate-In',
    vehicle: 'GJ-27-CH-8804',
    vehicleType: 'Container Truck',
    driver: 'Rafiq Shaikh',
    driverContact: '+91 99306 77410',
    transporter: 'Delhivery',
    vendor: 'Supreme Petrochem',
    orderId: 'ORD-2047',
    plant: 'Delhi',
    gate: 'Hazardous Material Gate',
    zone: 'QC Hold Area',
    material: 'Polymer granulate — 42 pallets',
    status: 'Blocked',
    entryAt: at('07:30'),
    expectedExit: at('12:30'),
    exitAt: null,
    pass: { id: 'SP-2190', holder: 'Rafiq Shaikh', validTo: '2026-10-14', status: 'Verified' },
    weighment: { grossKg: 28640, tareKg: 12480 },
    labourIn: 8,
    labourOut: 0,
    remarks: 'Consignment moved to the QC hold area after the shortfall was raised.',
    photos: ['Seal condition', 'Damaged pallet 3', 'Packing list'],
    documents: docs([
      ['Weighment Slip', 'Weighment', 'Verified'],
      ['Packing List', 'Packing List', 'Submitted'],
      ['Damage Evidence', 'Inspection Report', 'Submitted'],
    ]),
    activity: log('GT-4105', [
      ['Priya Nair', 'raised a QC rejection for 4 damaged units', '11:05'],
      ['Ravi Menon', 'recorded a shortfall of 8 units against the dispatch note', '10:40'],
      ['Gate Desk', 'completed weighment at Weighbridge 1', '08:15'],
    ]),
    stages: buildJourney('Gate-In', 3, 'blocked', {
      entry: at('07:30'),
      security: at('07:48'),
      weighment: at('08:15'),
    }),
    blockedReason: '8 units short and 4 damaged against the dispatch note — QC rejection raised.',
  },
  {
    id: 'GT-4102',
    direction: 'Gate-In',
    vehicle: 'MH-04-CD-8890',
    vehicleType: 'Trailer',
    driver: 'Vinod Kamble',
    driverContact: '+91 98675 20031',
    transporter: 'VRL Logistics',
    vendor: 'Kirloskar Brothers',
    orderId: 'ORD-2044',
    plant: 'Nagpur',
    gate: 'Gate 1',
    zone: 'Unloading Bay 3',
    material: 'Pump castings — 150 units',
    status: 'Delayed',
    entryAt: at('06:40'),
    expectedExit: at('11:00'),
    exitAt: null,
    pass: { id: 'SP-2168', holder: 'Vinod Kamble', validTo: '2026-09-02', status: 'Verified' },
    weighment: { grossKg: 31200, tareKg: 13950 },
    labourIn: 12,
    labourOut: 0,
    remarks: 'Unloading crew reassigned from the adjacent bay.',
    photos: ['Bay allocation', 'Consignment condition'],
    documents: docs([
      ['Gate Pass', 'Gate Pass', 'Verified'],
      ['Weighment Slip', 'Weighment', 'Verified'],
    ]),
    activity: log('GT-4102', [
      ['Ravi Menon', 'reported an unloading crew shortage in Bay 3', '11:10'],
      ['Gate Desk', 'completed weighment at Weighbridge 2', '07:25'],
      ['Gate Desk', 'recorded arrival at Gate 1', '06:40'],
    ]),
    stages: buildJourney('Gate-In', 4, 'delayed', {
      entry: at('06:40'),
      security: at('06:58'),
      weighment: at('07:25'),
      qc: at('09:10'),
    }),
    delayMinutes: 140,
  },
  {
    id: 'GT-4106',
    direction: 'Gate-In',
    vehicle: 'MH-46-AT-1129',
    vehicleType: 'Tanker',
    driver: 'Ganesh Patil',
    driverContact: '+91 90045 88123',
    transporter: 'Blue Dart',
    vendor: 'Praj Industries',
    orderId: 'ORD-2042',
    plant: 'Delhi',
    gate: 'Gate 1',
    zone: 'Weighbridge 1',
    material: 'Process solvent — 18 KL',
    status: 'Delayed',
    entryAt: at('10:55'),
    expectedExit: at('13:00'),
    exitAt: null,
    pass: { id: 'SP-2203', holder: 'Ganesh Patil', validTo: '2026-08-30', status: 'Verified' },
    weighment: { grossKg: 26800, tareKg: null },
    labourIn: 3,
    labourOut: 0,
    remarks: 'Arrived four days behind the carrier commitment.',
    photos: ['Tanker seal'],
    documents: docs([['Gate Pass', 'Gate Pass', 'Verified']]),
    activity: log('GT-4106', [
      ['Gate Desk', 'started weighment at Weighbridge 1', '12:35'],
      ['Amit Kulkarni', 'cleared security for the tanker consignment', '11:12'],
    ]),
    stages: buildJourney('Gate-In', 2, 'delayed', { entry: at('10:55'), security: at('11:12') }),
    delayMinutes: 95,
  },
  {
    id: 'GT-4101',
    direction: 'Gate-In',
    vehicle: 'GJ-01-AB-4521',
    vehicleType: 'Trailer',
    driver: 'Mahesh Solanki',
    driverContact: '+91 98250 11784',
    transporter: 'Safexpress',
    vendor: 'Larsen & Toubro',
    orderId: 'ORD-2041',
    plant: 'Jamnagar',
    gate: 'Gate 2',
    zone: 'QC Bay 1',
    material: 'Fabricated skid assemblies',
    status: 'On Site',
    entryAt: at('08:12'),
    expectedExit: at('14:30'),
    exitAt: null,
    pass: { id: 'SP-2151', holder: 'Mahesh Solanki', validTo: '2026-11-20', status: 'Verified' },
    weighment: { grossKg: 34500, tareKg: 14200 },
    labourIn: 9,
    labourOut: 0,
    remarks: null,
    photos: ['Consignment overview', 'Skid tag'],
    documents: docs([
      ['Gate Pass', 'Gate Pass', 'Verified'],
      ['Weighment Slip', 'Weighment', 'Verified'],
      ['Test Certificate', 'Certificate', 'Verified'],
    ]),
    activity: log('GT-4101', [
      ['Priya Nair', 'started inspection on the skid assemblies', '11:45'],
      ['Gate Desk', 'completed weighment at Weighbridge 2', '09:05'],
      ['Amit Kulkarni', 'verified the security pass at Gate 2', '08:30'],
    ]),
    stages: buildJourney('Gate-In', 3, 'none', {
      entry: at('08:12'),
      security: at('08:30'),
      weighment: at('09:05'),
    }),
  },
  {
    id: 'GT-4104',
    direction: 'Gate-Out',
    vehicle: 'MH-12-KL-7741',
    vehicleType: 'Flatbed',
    driver: 'Deepak Rane',
    driverContact: '+91 97690 33218',
    transporter: 'TCI Express',
    vendor: 'Thermax Ltd',
    orderId: 'ORD-2043',
    plant: 'Hyderabad',
    gate: 'Gate 4',
    zone: 'Loading Bay 2',
    material: 'Empty returnable frames',
    status: 'On Site',
    entryAt: at('10:20'),
    expectedExit: at('15:45'),
    exitAt: null,
    pass: { id: 'SP-2221', holder: 'Deepak Rane', validTo: '2026-12-05', status: 'Verified' },
    weighment: { grossKg: null, tareKg: 11800 },
    labourIn: 5,
    labourOut: 0,
    remarks: null,
    photos: ['Loading bay allocation'],
    documents: docs([['Gate Pass', 'Gate Pass', 'Verified']]),
    activity: log('GT-4104', [
      ['Ravi Menon', 'allocated Loading Bay 2', '10:52'],
      ['Gate Desk', 'recorded arrival at Gate 4', '10:20'],
    ]),
    stages: buildJourney('Gate-Out', 2, 'none', { entry: at('10:20'), security: at('10:41') }),
  },
  {
    id: 'GT-4108',
    direction: 'Gate-In',
    vehicle: 'MH-04-PQ-9032',
    vehicleType: 'Container Truck',
    driver: 'Irfan Ansari',
    driverContact: '+91 98332 47710',
    transporter: 'VRL Logistics',
    vendor: 'Bharat Heavy Electricals',
    orderId: 'ORD-2048',
    plant: 'Hyderabad',
    gate: 'Gate 2',
    zone: 'Entry Lane 2',
    material: 'Turbine spares — 6 crates',
    status: 'On Site',
    entryAt: at('12:58'),
    expectedExit: at('17:30'),
    exitAt: null,
    pass: { id: 'SP-2230', holder: 'Irfan Ansari', validTo: '2026-08-14', status: 'Verified' },
    weighment: { grossKg: null, tareKg: null },
    labourIn: 2,
    labourOut: 0,
    remarks: null,
    photos: [],
    documents: docs([['Gate Pass', 'Gate Pass', 'Submitted']]),
    activity: log('GT-4108', [['Gate Desk', 'recorded arrival at Gate 2', '12:58']]),
    stages: buildJourney('Gate-In', 0, 'none', {}),
  },
  {
    id: 'GT-4109',
    direction: 'Gate-In',
    vehicle: 'GJ-18-TC-2290',
    vehicleType: 'Trailer',
    driver: 'Sanjay Bhatt',
    driverContact: '+91 99786 10023',
    transporter: 'Gati',
    vendor: 'Larsen & Toubro',
    orderId: 'ORD-2049',
    plant: 'Hyderabad',
    gate: 'Gate 2',
    zone: 'Exit Lane 1',
    material: 'Structural steel sections',
    status: 'Awaiting Exit',
    entryAt: at('05:50'),
    expectedExit: at('13:30'),
    exitAt: null,
    pass: { id: 'SP-2144', holder: 'Sanjay Bhatt', validTo: '2026-10-01', status: 'Verified' },
    weighment: { grossKg: 38700, tareKg: 15600 },
    labourIn: 11,
    labourOut: 11,
    remarks: 'Awaiting exit weighment clearance.',
    photos: ['Empty bed confirmation'],
    documents: docs([
      ['Gate Pass', 'Gate Pass', 'Verified'],
      ['Weighment Slip', 'Weighment', 'Verified'],
      ['Unloading Confirmation', 'Report', 'Verified'],
    ]),
    activity: log('GT-4109', [
      ['Ravi Menon', 'closed unloading and released the vehicle', '12:40'],
      ['Priya Nair', 'passed inspection on the steel sections', '10:20'],
    ]),
    stages: buildJourney('Gate-In', 5, 'none', {
      entry: at('05:50'),
      security: at('06:05'),
      weighment: at('06:30'),
      qc: at('10:20'),
      unloading: at('12:40'),
    }),
  },
  {
    id: 'GT-4114',
    direction: 'Gate-In',
    vehicle: 'MH-20-JK-8817',
    vehicleType: 'Container Truck',
    driver: 'Prakash Nayak',
    driverContact: '+91 98110 55204',
    transporter: 'Blue Dart',
    vendor: 'ISGEC Heavy Engineering',
    orderId: 'ORD-2064',
    plant: 'Jamnagar',
    gate: 'Gate 1',
    zone: 'Cleared site',
    material: 'Pressure vessel internals',
    status: 'Exited',
    entryAt: at('06:15'),
    expectedExit: at('11:30'),
    exitAt: at('11:30'),
    pass: { id: 'SP-2137', holder: 'Prakash Nayak', validTo: '2026-09-18', status: 'Verified' },
    weighment: { grossKg: 29400, tareKg: 13100 },
    labourIn: 7,
    labourOut: 7,
    remarks: null,
    photos: ['Exit confirmation'],
    documents: docs([
      ['Gate Pass', 'Gate Pass', 'Verified'],
      ['Weighment Slip', 'Weighment', 'Verified'],
    ]),
    activity: log('GT-4114', [
      ['Gate Desk', 'closed the movement at Gate 1', '11:30'],
      ['Ravi Menon', 'confirmed unloading complete', '10:55'],
    ]),
    stages: buildJourney('Gate-In', 6, 'none', {
      entry: at('06:15'),
      security: at('06:32'),
      weighment: at('06:58'),
      qc: at('09:20'),
      unloading: at('10:55'),
      exit: at('11:30'),
    }),
  },
  {
    id: 'GT-4107',
    direction: 'Gate-Out',
    vehicle: 'GJ-01-XY-6650',
    vehicleType: 'Flatbed',
    driver: 'Nitin Chavda',
    driverContact: '+91 99042 66810',
    transporter: 'Safexpress',
    vendor: 'ISGEC Heavy Engineering',
    orderId: 'ORD-2046',
    plant: 'Surat',
    gate: 'Gate 3',
    zone: 'Cleared site',
    material: 'Returnable packing frames',
    status: 'Exited',
    entryAt: at('07:05'),
    expectedExit: at('09:45'),
    exitAt: at('09:50'),
    pass: { id: 'SP-2129', holder: 'Nitin Chavda', validTo: '2026-08-28', status: 'Verified' },
    weighment: { grossKg: 18200, tareKg: 11400 },
    labourIn: 4,
    labourOut: 4,
    remarks: null,
    photos: [],
    documents: docs([['Gate Pass', 'Gate Pass', 'Verified']]),
    activity: log('GT-4107', [['Gate Desk', 'closed the movement at Gate 3', '09:50']]),
    stages: buildJourney('Gate-Out', 5, 'none', {
      entry: at('07:05'),
      security: at('07:20'),
      loading: at('08:40'),
      weighment: at('09:25'),
      exit: at('09:50'),
    }),
  },
  {
    id: 'GT-4110',
    direction: 'Gate-Out',
    vehicle: 'MH-14-RS-4407',
    vehicleType: 'LCV',
    driver: 'Bhaskar Jadhav',
    driverContact: '+91 98220 74451',
    transporter: 'TCI Express',
    vendor: 'Kirloskar Brothers',
    orderId: 'ORD-2058',
    plant: 'Hyderabad',
    gate: 'Gate 4',
    zone: 'Cleared site',
    material: 'Rejected castings — return to vendor',
    status: 'Exited',
    entryAt: at('06:20'),
    expectedExit: at('08:30'),
    exitAt: at('08:25'),
    pass: { id: 'SP-2133', holder: 'Bhaskar Jadhav', validTo: '2026-09-11', status: 'Verified' },
    weighment: { grossKg: 9400, tareKg: 6100 },
    labourIn: 3,
    labourOut: 3,
    remarks: 'Return consignment against the governance review.',
    photos: ['Return manifest'],
    documents: docs([
      ['Gate Pass', 'Gate Pass', 'Verified'],
      ['Return Manifest', 'Report', 'Verified'],
    ]),
    activity: log('GT-4110', [['Gate Desk', 'closed the movement at Gate 4', '08:25']]),
    stages: buildJourney('Gate-Out', 5, 'none', {
      entry: at('06:20'),
      security: at('06:35'),
      loading: at('07:30'),
      weighment: at('08:05'),
      exit: at('08:25'),
    }),
  },
  {
    id: 'GT-4113',
    direction: 'Gate-Out',
    vehicle: 'GJ-09-MN-3341',
    vehicleType: 'Tanker',
    driver: 'Alok Mishra',
    driverContact: '+91 90493 18820',
    transporter: 'Gati',
    vendor: 'Supreme Petrochem',
    orderId: 'ORD-2060',
    plant: 'Delhi',
    gate: 'Gate 1',
    zone: 'Cleared site',
    material: 'Empty tanker return',
    status: 'Exited',
    entryAt: at('06:05'),
    expectedExit: at('08:00'),
    exitAt: at('07:55'),
    pass: { id: 'SP-2126', holder: 'Alok Mishra', validTo: '2026-08-22', status: 'Verified' },
    weighment: { grossKg: 14100, tareKg: 13900 },
    labourIn: 2,
    labourOut: 2,
    remarks: null,
    photos: [],
    documents: docs([['Gate Pass', 'Gate Pass', 'Verified']]),
    activity: log('GT-4113', [['Gate Desk', 'closed the movement at Gate 1', '07:55']]),
    stages: buildJourney('Gate-Out', 5, 'none', {
      entry: at('06:05'),
      security: at('06:18'),
      loading: at('06:50'),
      weighment: at('07:35'),
      exit: at('07:55'),
    }),
  },
  {
    id: 'GT-4111',
    direction: 'Gate-In',
    vehicle: 'GJ-06-DL-7712',
    vehicleType: 'Trailer',
    driver: 'Hitesh Parmar',
    driverContact: '+91 98795 22140',
    transporter: 'Delhivery',
    vendor: 'Thermax Ltd',
    orderId: 'ORD-2059',
    plant: 'Jamnagar',
    gate: 'Gate 1',
    zone: 'Expected at Gate 1',
    material: 'Boiler drum assembly',
    status: 'Scheduled',
    entryAt: null,
    expectedExit: at('19:00'),
    exitAt: null,
    pass: { id: 'SP-2238', holder: 'Hitesh Parmar', validTo: '2026-08-05', status: 'Expiring' },
    weighment: { grossKg: null, tareKg: null },
    labourIn: 0,
    labourOut: 0,
    remarks: 'Arrival slot confirmed with the transporter for 15:30.',
    photos: [],
    documents: docs([['Advance Shipping Note', 'Report', 'Submitted']]),
    activity: log('GT-4111', [['Vendor Coordinator', 'confirmed the 15:30 arrival slot', '09:40']]),
    stages: buildJourney('Gate-In', -1, 'none', {}),
  },
  {
    id: 'GT-4112',
    direction: 'Gate-In',
    vehicle: 'MH-31-EF-5560',
    vehicleType: 'Flatbed',
    driver: 'Yogesh Salvi',
    driverContact: '+91 90291 60074',
    transporter: 'Blue Dart',
    vendor: 'TEMA India',
    orderId: 'ORD-2062',
    plant: 'Surat',
    gate: 'Gate 3',
    zone: 'Expected at Gate 3',
    material: 'Tube bundle crates',
    status: 'Scheduled',
    entryAt: null,
    expectedExit: at('21:00'),
    exitAt: null,
    pass: { id: 'SP-2241', holder: 'Yogesh Salvi', validTo: '2026-11-02', status: 'Verified' },
    weighment: { grossKg: null, tareKg: null },
    labourIn: 0,
    labourOut: 0,
    remarks: 'Arrival slot confirmed with the transporter for 17:15.',
    photos: [],
    documents: docs([['Advance Shipping Note', 'Report', 'Submitted']]),
    activity: log('GT-4112', [['Vendor Coordinator', 'confirmed the 17:15 arrival slot', '10:15']]),
    stages: buildJourney('Gate-In', -1, 'none', {}),
  },
];

/** Scheduled arrivals carry the slot they are expected in, read by the context panel. */
export const SCHEDULED_ARRIVAL: Record<string, string> = {
  'GT-4111': at('15:30'),
  'GT-4112': at('17:15'),
};

export const MANPOWER: ManpowerRecord[] = [
  {
    id: 'MP-3301',
    vendor: 'Larsen & Toubro',
    plant: 'Jamnagar',
    zone: 'Zone A — Unit 4',
    supervisor: 'Rakesh Pawar',
    supervisorContact: '+91 98250 40012',
    current: 128,
    enteredToday: 142,
    exitedToday: 14,
    shift: 'General · 07:00 – 19:00',
    trades: [
      { label: 'Fitter', count: 46 },
      { label: 'Welder', count: 32 },
      { label: 'Rigger', count: 24 },
      { label: 'Helper', count: 26 },
    ],
    inductionValidTo: '2026-09-30',
    passesExpiring: 3,
    orderId: 'ORD-2041',
  },
  {
    id: 'MP-3302',
    vendor: 'Bharat Heavy Electricals',
    plant: 'Hyderabad',
    zone: 'Zone B — Turbine Bay',
    supervisor: 'Farhan Qureshi',
    supervisorContact: '+91 98332 77190',
    current: 88,
    enteredToday: 92,
    exitedToday: 4,
    shift: 'General · 07:00 – 19:00',
    trades: [
      { label: 'Millwright', count: 30 },
      { label: 'Electrician', count: 22 },
      { label: 'Fitter', count: 20 },
      { label: 'Helper', count: 16 },
    ],
    inductionValidTo: '2026-08-18',
    passesExpiring: 6,
    orderId: 'ORD-2048',
  },
  {
    id: 'MP-3303',
    vendor: 'Thermax Ltd',
    plant: 'Hyderabad',
    zone: 'Zone B — Boiler Yard',
    supervisor: 'Imran Sheikh',
    supervisorContact: '+91 99870 21145',
    current: 96,
    enteredToday: 104,
    exitedToday: 8,
    shift: 'Shift A · 06:00 – 14:00',
    trades: [
      { label: 'Welder', count: 38 },
      { label: 'Fabricator', count: 28 },
      { label: 'Rigger', count: 18 },
      { label: 'Helper', count: 12 },
    ],
    inductionValidTo: '2026-10-12',
    passesExpiring: 1,
    orderId: 'ORD-2043',
  },
  {
    id: 'MP-3304',
    vendor: 'Kirloskar Brothers',
    plant: 'Nagpur',
    zone: 'Zone C — Pump House',
    supervisor: 'Anita Deshmukh',
    supervisorContact: '+91 98675 33210',
    current: 74,
    enteredToday: 80,
    exitedToday: 6,
    shift: 'General · 07:00 – 19:00',
    trades: [
      { label: 'Fitter', count: 28 },
      { label: 'Machinist', count: 20 },
      { label: 'Electrician', count: 14 },
      { label: 'Helper', count: 12 },
    ],
    inductionValidTo: '2026-11-05',
    passesExpiring: 0,
    orderId: 'ORD-2044',
  },
  {
    id: 'MP-3305',
    vendor: 'ISGEC Heavy Engineering',
    plant: 'Surat',
    zone: 'Zone D — Fabrication',
    supervisor: 'Joseph Mathew',
    supervisorContact: '+91 99042 11876',
    current: 58,
    enteredToday: 61,
    exitedToday: 3,
    shift: 'Shift A · 06:00 – 14:00',
    trades: [
      { label: 'Welder', count: 24 },
      { label: 'Fabricator', count: 18 },
      { label: 'Painter', count: 9 },
      { label: 'Helper', count: 7 },
    ],
    inductionValidTo: '2026-09-08',
    passesExpiring: 2,
    orderId: 'ORD-2046',
  },
  {
    id: 'MP-3306',
    vendor: 'Supreme Petrochem',
    plant: 'Delhi',
    zone: 'Zone E — Tank Farm',
    supervisor: 'Vikram Chauhan',
    supervisorContact: '+91 90493 55021',
    current: 42,
    enteredToday: 55,
    exitedToday: 13,
    shift: 'Shift B · 14:00 – 22:00',
    trades: [
      { label: 'Operator', count: 16 },
      { label: 'Fitter', count: 12 },
      { label: 'Safety Steward', count: 8 },
      { label: 'Helper', count: 6 },
    ],
    inductionValidTo: '2026-08-02',
    passesExpiring: 5,
    orderId: 'ORD-2047',
  },
];

export const MOVEMENT_STATUS_ORDER: MovementStatus[] = [
  'Blocked',
  'Delayed',
  'Awaiting Exit',
  'On Site',
  'Scheduled',
  'Exited',
];
