import type { Vendor, VendorCategory } from '../types/vendor';

/* The first eight entries are the vendors that already appear in the order
   register (mockData/orders.ts). The directory has to name them identically so
   a vendor row and an order row can never disagree about who the vendor is. */
export const VENDORS: Vendor[] = [
  {
    id: 'VND-1001',
    name: 'Larsen & Toubro',
    code: 'LNT-IN',
    category: 'Static Equipment',
    plants: ['Jamnagar', 'Surat', 'Nagpur'],
    compliance: 98,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-29',
  },
  {
    id: 'VND-1002',
    name: 'Thermax Ltd',
    code: 'THX-IN',
    category: 'Heat Exchangers',
    plants: ['Jamnagar', 'Hyderabad'],
    compliance: 94,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-28',
  },
  {
    id: 'VND-1003',
    name: 'Kirloskar Brothers',
    code: 'KBL-IN',
    category: 'Rotating Equipment',
    plants: ['Delhi', 'Nagpur'],
    compliance: 81,
    complianceState: 'Expiring',
    risk: 'Medium',
    status: 'Active',
    lastActivity: '2026-07-27',
  },
  {
    id: 'VND-1004',
    name: 'Bharat Heavy Electricals',
    code: 'BHEL-IN',
    category: 'Electricals',
    plants: ['Jamnagar', 'Delhi', 'Hyderabad', 'Surat'],
    compliance: 96,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-30',
  },
  {
    id: 'VND-1005',
    name: 'Praj Industries',
    code: 'PRAJ-IN',
    category: 'Static Equipment',
    plants: ['Surat'],
    compliance: 72,
    complianceState: 'Pending KYC',
    risk: 'Medium',
    status: 'Onboarding',
    lastActivity: '2026-07-24',
  },
  {
    id: 'VND-1006',
    name: 'TEMA India',
    code: 'TEMA-IN',
    category: 'Heat Exchangers',
    plants: ['Nagpur'],
    compliance: 58,
    complianceState: 'Pending KYC',
    risk: 'High',
    status: 'Onboarding',
    lastActivity: '2026-07-21',
  },
  {
    id: 'VND-1007',
    name: 'ISGEC Heavy Engineering',
    code: 'ISGC-IN',
    category: 'Static Equipment',
    plants: ['Jamnagar', 'Nagpur'],
    compliance: 88,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-26',
  },
  {
    id: 'VND-1008',
    name: 'Supreme Petrochem',
    code: 'SPCL-IN',
    category: 'Bulk Chemicals',
    plants: ['Jamnagar', 'Surat'],
    compliance: 64,
    complianceState: 'Expired',
    risk: 'High',
    status: 'Suspended',
    lastActivity: '2026-06-30',
  },
  {
    id: 'VND-1009',
    name: 'Godrej Process Equipment',
    code: 'GPEQ-IN',
    category: 'Static Equipment',
    plants: ['Jamnagar', 'Hyderabad'],
    compliance: 92,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-25',
  },
  {
    id: 'VND-1010',
    name: 'Alfa Laval India',
    code: 'ALFA-IN',
    category: 'Heat Exchangers',
    plants: ['Delhi', 'Surat'],
    compliance: 90,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-23',
  },
  {
    id: 'VND-1011',
    name: 'Grasim Industries',
    code: 'GRAS-IN',
    category: 'Bulk Chemicals',
    plants: ['Jamnagar', 'Nagpur', 'Surat'],
    compliance: 86,
    complianceState: 'Verified',
    risk: 'Medium',
    status: 'Active',
    lastActivity: '2026-07-22',
  },
  {
    id: 'VND-1012',
    name: 'Sud-Chemie Catalysts',
    code: 'SUDC-IN',
    category: 'Catalysts',
    plants: ['Jamnagar'],
    compliance: 77,
    complianceState: 'Expiring',
    risk: 'Medium',
    status: 'Active',
    lastActivity: '2026-07-20',
  },
  {
    id: 'VND-1013',
    name: 'Emerson Automation',
    code: 'EMRS-IN',
    category: 'Instrumentation',
    plants: ['Hyderabad', 'Delhi'],
    compliance: 95,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-29',
  },
  {
    id: 'VND-1014',
    name: 'Yokogawa India',
    code: 'YOKO-IN',
    category: 'Instrumentation',
    plants: ['Surat'],
    compliance: 69,
    complianceState: 'Pending KYC',
    risk: 'Medium',
    status: 'Onboarding',
    lastActivity: '2026-07-18',
  },
  {
    id: 'VND-1015',
    name: 'Simplex Infrastructures',
    code: 'SMPX-IN',
    category: 'Civil & Structural',
    plants: ['Nagpur', 'Delhi'],
    compliance: 54,
    complianceState: 'Expired',
    risk: 'High',
    status: 'Inactive',
    lastActivity: '2026-05-14',
  },
  {
    id: 'VND-1016',
    name: 'Uflex Packaging',
    code: 'UFLX-IN',
    category: 'Packaging',
    plants: ['Delhi', 'Hyderabad', 'Surat'],
    compliance: 83,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-19',
  },
  {
    id: 'VND-1017',
    name: 'Allcargo Logistics',
    code: 'ALCG-IN',
    category: 'Logistics',
    plants: ['Jamnagar', 'Delhi', 'Hyderabad', 'Nagpur', 'Surat'],
    compliance: 89,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-30',
  },
  {
    id: 'VND-1018',
    name: 'Flowserve India',
    code: 'FLSV-IN',
    category: 'Rotating Equipment',
    plants: ['Jamnagar', 'Surat'],
    compliance: 61,
    complianceState: 'Pending KYC',
    risk: 'High',
    status: 'Onboarding',
    lastActivity: '2026-07-15',
  },
  {
    id: 'VND-1019',
    name: 'Siemens Energy India',
    code: 'SIEM-IN',
    category: 'Electricals',
    plants: ['Hyderabad', 'Nagpur'],
    compliance: 93,
    complianceState: 'Verified',
    risk: 'Low',
    status: 'Active',
    lastActivity: '2026-07-27',
  },
  {
    id: 'VND-1020',
    name: 'Tata Projects',
    code: 'TATP-IN',
    category: 'Civil & Structural',
    plants: ['Jamnagar', 'Surat', 'Delhi'],
    compliance: 79,
    complianceState: 'Expiring',
    risk: 'Medium',
    status: 'Active',
    lastActivity: '2026-07-16',
  },
];

export const VENDOR_CATEGORIES: VendorCategory[] = Array.from(
  new Set(VENDORS.map((vendor) => vendor.category)),
).sort() as VendorCategory[];
