import type { Workflow, WorkflowKey, WorkflowRole, WorkflowStage } from '../types/workflow';

export const CONTRACT_TYPES = [
  'Manufactured Supply',
  'Material Supply',
  'Turnkey Erection',
  'Service Contract',
];

export const DOCUMENT_LIBRARY = [
  'Gate Pass',
  'Tax Invoice',
  'E-Way Bill',
  'Test Certificate',
  'Weighment Slip',
  'Delivery Challan',
  'QC Report',
  'Insurance Certificate',
];

export const ESCALATION_RULES = [
  'No escalation',
  'Notify supervisor',
  'Escalate to plant head',
  'Escalate to governance',
];

export const AUTO_UNLOCK_RULES = [
  'Manual release only',
  'On previous stage completion',
  'On document upload',
  'On SLA breach',
];

export const NOTIFICATION_TRIGGERS = [
  'On stage entry',
  'On SLA breach',
  'On approval only',
  'Disabled',
];

export const WORKFLOW_ROLES: WorkflowRole[] = [
  {
    id: 'ROL-01',
    role: 'Security Officer',
    department: 'Security',
    responsibility: 'Vehicle validation and entry clearance at the plant boundary',
    stages: ['Security Clearance'],
    escalationLevel: 'L1',
    status: 'Active',
  },
  {
    id: 'ROL-02',
    role: 'Document Controller',
    department: 'Commercial',
    responsibility: 'Invoice, e-way bill and purchase order document checks',
    stages: ['Document Verification'],
    escalationLevel: 'L1',
    status: 'Active',
  },
  {
    id: 'ROL-03',
    role: 'Gate Supervisor',
    department: 'Logistics',
    responsibility: 'Gate-in registration and weighbridge capture',
    stages: ['Gate-In'],
    escalationLevel: 'L2',
    status: 'Active',
  },
  {
    id: 'ROL-04',
    role: 'Quality Inspector',
    department: 'Quality',
    responsibility: 'Material inspection and QC disposition against specification',
    stages: ['QC'],
    escalationLevel: 'L2',
    status: 'Active',
  },
  {
    id: 'ROL-05',
    role: 'Site Coordinator',
    department: 'Site Operations',
    responsibility: 'Unloading confirmation and delivery closure at site',
    stages: ['Delivery'],
    escalationLevel: 'L1',
    status: 'Active',
  },
  {
    id: 'ROL-06',
    role: 'Governance Lead',
    department: 'Governance',
    responsibility: 'Deviation approval and exception sign-off before payment',
    stages: ['Governance'],
    escalationLevel: 'L3',
    status: 'Active',
  },
  {
    id: 'ROL-07',
    role: 'Finance Controller',
    department: 'Finance',
    responsibility: 'Three-way invoice matching and payment release',
    stages: ['Payment'],
    escalationLevel: 'L3',
    status: 'Active',
  },
];

export const ROLE_NAMES = WORKFLOW_ROLES.map((role) => role.role);

export const STAGE_LIBRARY: Array<Pick<WorkflowStage, 'id' | 'name' | 'role' | 'slaHours' | 'documents' | 'escalation'>> = [
  {
    id: 'security-clearance',
    name: 'Security Clearance',
    role: 'Security Officer',
    slaHours: 2,
    documents: ['Gate Pass'],
    escalation: 'Notify supervisor',
  },
  {
    id: 'document-verification',
    name: 'Document Verification',
    role: 'Document Controller',
    slaHours: 4,
    documents: ['Tax Invoice', 'E-Way Bill'],
    escalation: 'Notify supervisor',
  },
  {
    id: 'gate-in',
    name: 'Material Gate-In',
    role: 'Gate Supervisor',
    slaHours: 3,
    documents: ['Weighment Slip'],
    escalation: 'Escalate to plant head',
  },
  {
    id: 'weighment',
    name: 'Weighment',
    role: 'Gate Supervisor',
    slaHours: 2,
    documents: ['Weighment Slip'],
    escalation: 'Notify supervisor',
  },
  {
    id: 'qc',
    name: 'QC Inspection',
    role: 'Quality Inspector',
    slaHours: 12,
    documents: ['Test Certificate', 'QC Report'],
    escalation: 'Escalate to plant head',
  },
  {
    id: 'unloading',
    name: 'Unloading',
    role: 'Site Coordinator',
    slaHours: 4,
    documents: ['Delivery Challan'],
    escalation: 'Notify supervisor',
  },
  {
    id: 'delivery',
    name: 'Delivery',
    role: 'Site Coordinator',
    slaHours: 8,
    documents: ['Delivery Challan'],
    escalation: 'Notify supervisor',
  },
  {
    id: 'governance',
    name: 'Governance Approval',
    role: 'Governance Lead',
    slaHours: 24,
    documents: [],
    escalation: 'Escalate to governance',
  },
  {
    id: 'payment',
    name: 'Payment Release',
    role: 'Finance Controller',
    slaHours: 48,
    documents: ['Tax Invoice'],
    escalation: 'Escalate to governance',
  },
];

const MANUFACTURED_STAGES: WorkflowStage[] = [
  {
    id: 'security-clearance',
    name: 'Security Clearance',
    role: 'Security Officer',
    dependency: 'none',
    slaHours: 2,
    escalation: 'Notify supervisor',
    documents: ['Gate Pass'],
    autoUnlock: 'Manual release only',
    mandatory: true,
  },
  {
    id: 'document-verification',
    name: 'Document Verification',
    role: 'Document Controller',
    dependency: 'security-clearance',
    slaHours: 4,
    escalation: 'Notify supervisor',
    documents: ['Tax Invoice', 'E-Way Bill'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
  {
    id: 'gate-in',
    name: 'Material Gate-In',
    role: 'Gate Supervisor',
    dependency: 'document-verification',
    slaHours: 3,
    escalation: 'Escalate to plant head',
    documents: ['Weighment Slip'],
    autoUnlock: 'On document upload',
    mandatory: true,
  },
  {
    id: 'qc',
    name: 'QC Inspection',
    role: 'Quality Inspector',
    dependency: 'gate-in',
    slaHours: 12,
    escalation: 'Escalate to plant head',
    documents: ['Test Certificate', 'QC Report'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
  {
    id: 'delivery',
    name: 'Delivery',
    role: 'Site Coordinator',
    dependency: 'qc',
    slaHours: 8,
    escalation: 'Notify supervisor',
    documents: ['Delivery Challan'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
  {
    id: 'governance',
    name: 'Governance Approval',
    role: 'Governance Lead',
    dependency: 'delivery',
    slaHours: 24,
    escalation: 'Escalate to governance',
    documents: [],
    autoUnlock: 'Manual release only',
    mandatory: false,
  },
  {
    id: 'payment',
    name: 'Payment Release',
    role: 'Finance Controller',
    dependency: 'governance',
    slaHours: 48,
    escalation: 'Escalate to governance',
    documents: ['Tax Invoice'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
];

const MATERIAL_STAGES: WorkflowStage[] = [
  {
    id: 'security-clearance',
    name: 'Security Clearance',
    role: 'Security Officer',
    dependency: 'none',
    slaHours: 1,
    escalation: 'Notify supervisor',
    documents: ['Gate Pass'],
    autoUnlock: 'Manual release only',
    mandatory: true,
  },
  {
    id: 'document-verification',
    name: 'Document Verification',
    role: 'Document Controller',
    dependency: 'security-clearance',
    slaHours: 2,
    escalation: 'No escalation',
    documents: ['Tax Invoice', 'E-Way Bill', 'Insurance Certificate'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
  {
    id: 'gate-in',
    name: 'Material Gate-In',
    role: 'Gate Supervisor',
    dependency: 'document-verification',
    slaHours: 2,
    escalation: 'Notify supervisor',
    documents: ['Weighment Slip'],
    autoUnlock: 'On document upload',
    mandatory: true,
  },
  {
    id: 'qc',
    name: 'QC Inspection',
    role: 'Quality Inspector',
    dependency: 'gate-in',
    slaHours: 6,
    escalation: 'Escalate to plant head',
    documents: ['Test Certificate'],
    autoUnlock: 'On previous stage completion',
    mandatory: false,
  },
  {
    id: 'delivery',
    name: 'Delivery',
    role: 'Site Coordinator',
    dependency: 'qc',
    slaHours: 6,
    escalation: 'Notify supervisor',
    documents: ['Delivery Challan'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
  {
    id: 'governance',
    name: 'Governance Approval',
    role: 'Governance Lead',
    dependency: 'delivery',
    slaHours: 18,
    escalation: 'Escalate to governance',
    documents: [],
    autoUnlock: 'Manual release only',
    mandatory: false,
  },
  {
    id: 'payment',
    name: 'Payment Release',
    role: 'Finance Controller',
    dependency: 'governance',
    slaHours: 36,
    escalation: 'Escalate to governance',
    documents: ['Tax Invoice'],
    autoUnlock: 'On previous stage completion',
    mandatory: true,
  },
];

export const WORKFLOWS: Record<WorkflowKey, Workflow> = {
  manufactured: {
    key: 'manufactured',
    label: 'Manufactured Workflow',
    contractType: 'Manufactured Supply',
    status: 'Active',
    stages: MANUFACTURED_STAGES,
    rules: {
      autoProgression: true,
      parallelApprovals: false,
      manualApproval: true,
      escalationEnabled: true,
      notification: 'On stage entry',
    },
  },
  material: {
    key: 'material',
    label: 'Material Workflow',
    contractType: 'Material Supply',
    status: 'Draft',
    stages: MATERIAL_STAGES,
    rules: {
      autoProgression: true,
      parallelApprovals: true,
      manualApproval: false,
      escalationEnabled: true,
      notification: 'On SLA breach',
    },
  },
};
