import { useState } from 'react';
import { CheckCircle2, ClipboardCheck, Clock, Eye, FileText } from 'lucide-react';

import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';
import DocumentRow from '../../components/ui/DocumentRow';
import KeyValue from '../../components/ui/KeyValue';
import Modal from '../../components/ui/Modal';
import ProgressMeter from '../../components/ui/ProgressMeter';
import Section from '../../components/ui/Section';
import { formatDate } from '../../lib/format';
import { buildPcfRecord, recordPcfArtefacts, type PcfChecklistItem } from '../../lib/pcf';
import { downloadPcfPdf } from '../../lib/pcfExport';
import type { Order } from '../../lib/types/order';
import type { OrderDetail } from '../../lib/types/orderDetail';

interface CompletionFileTabProps {
  order: Order;
  detail: OrderDetail;
  onNotify: (message: string) => void;
}

function ChecklistRow({ item, onView }: { item: PcfChecklistItem; onView: () => void }) {
  const complete = item.status === 'Complete';

  return (
    <div
      className="flex items-center gap-3.5 border-b border-[var(--color-glass-hairline)] px-5 py-3.5 last:border-b-0"
      style={complete ? undefined : { background: 'var(--color-surface-subtle)' }}
    >
      <span className="flex-none">
        {complete ? (
          <CheckCircle2 size={17} strokeWidth={2.2} style={{ color: 'var(--color-success)' }} />
        ) : (
          <Clock size={17} strokeWidth={2.2} style={{ color: 'var(--color-warning)' }} />
        )}
      </span>

      <div className="min-w-0 flex-1">
        <div className={complete ? 'text-body-strong truncate' : 'text-body truncate'}>{item.label}</div>
        <div className="text-meta truncate tabular-nums">
          {complete
            ? `${item.stage} · ${item.documents.length} document${item.documents.length === 1 ? '' : 's'}${
                item.completedAt ? ` · ${formatDate(item.completedAt)} · ${item.completedBy}` : ''
              }`
            : `${item.stage} · awaiting upload`}
        </div>
      </div>

      <Badge tone={complete ? 'success' : 'warning'} shape="square" size="sm" className="flex-none">
        {item.status}
      </Badge>

      <Button variant="ghost" size="sm" onClick={onView} className="flex-none cursor-pointer">
        View
      </Button>
    </div>
  );
}

export default function CompletionFileTab({ order, detail, onNotify }: CompletionFileTabProps) {
  const [, setRecorded] = useState(0);
  const record = buildPcfRecord(order, detail);
  const [preview, setPreview] = useState(false);
  const [item, setItem] = useState<PcfChecklistItem | null>(null);

  const ready = record.status === 'Complete';

  const summaryItems = [
    { label: 'Documents Collected', value: `${record.collected} of ${record.total}` },
    { label: 'Missing Documents', value: String(record.missing.length) },
    { label: 'Generated Date', value: record.generatedAt ? formatDate(record.generatedAt) : null },
    { label: 'Generated By', value: ready ? record.generatedBy : null },
  ];

  return (
    <>
      <Section
        variant="flush"
        title="Completion Summary"
        padded={false}
        actions={
          <Badge tone={ready ? 'success' : 'warning'} shape="square">
            {ready ? 'Complete' : 'Pending'}
          </Badge>
        }
      >
        <div className="p-5">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div className="min-w-0">
              <p className="text-eyebrow uppercase">Overall Completion</p>
              <p className="mt-1 text-[30px] leading-9 font-semibold tabular-nums text-ink-900">
                {record.completionPct}%
              </p>
            </div>
            <p className="text-meta tabular-nums">
              {ready
                ? `Assembled ${record.completionDate ? formatDate(record.completionDate) : ''}`.trim()
                : `${record.missing.length} artefact${record.missing.length === 1 ? '' : 's'} outstanding`}
            </p>
          </div>

          <ProgressMeter
            value={record.completionPct}
            tone={ready ? 'success' : 'warning'}
            className="mt-4"
          />

          <div className="mt-6 border-t border-[var(--color-border)] pt-5">
            <KeyValue columns={4} items={summaryItems} />
          </div>
        </div>
      </Section>

      <Section
        variant="flush"
        title="Project Completion Checklist"
        description="Artefacts collected automatically as each gate closes."
        padded={false}
      >
        {record.checklist.map((entry) => (
          <ChecklistRow key={entry.id} item={entry} onView={() => setItem(entry)} />
        ))}
      </Section>

      <Section variant="flush" title="Actions">
        <div className="flex flex-wrap items-center gap-2.5">
          <Button
            variant="secondary"
            icon={<Eye size={16} strokeWidth={2.2} />}
            className="cursor-pointer"
            onClick={() => setPreview(true)}
          >
            Preview PCF
          </Button>
          {!ready && (
            <Button
              variant="secondary"
              icon={<ClipboardCheck size={16} strokeWidth={2.2} />}
              className="cursor-pointer"
              onClick={() => {
                recordPcfArtefacts(order.id);
                setRecorded((value) => value + 1);
                onNotify(`Outstanding artefacts recorded against ${order.id}.`);
              }}
            >
              Record Pending Documents
            </Button>
          )}
          <Button
            variant="primary"
            icon={<FileText size={16} strokeWidth={2.2} />}
            className="cursor-pointer"
            onClick={() => {
              downloadPcfPdf(order, record);
              onNotify(`${order.id} project completion file downloaded as PDF.`);
            }}
          >
            Download PDF
          </Button>
        </div>
      </Section>

      <Modal
        open={preview}
        title={`${order.id} — Project Completion File`}
        description={`${order.vendor} · ${order.plant}`}
        onClose={() => setPreview(false)}
        width="760px"
        footer={
          <Button variant="secondary" className="cursor-pointer" onClick={() => setPreview(false)}>
            Close
          </Button>
        }
      >
        <div className="flex flex-col gap-6">
          <div>
            <ProgressMeter value={record.completionPct} tone={ready ? 'success' : 'warning'} />
            <div className="mt-4">
              <KeyValue
                columns={4}
                items={[
                  { label: 'Completion', value: `${record.completionPct}%` },
                  { label: 'Documents Collected', value: `${record.collected} of ${record.total}` },
                  { label: 'Missing Documents', value: String(record.missing.length) },
                  { label: 'Status', value: record.status },
                ]}
              />
            </div>
          </div>

          <div className="surface-section overflow-hidden">
            <header className="surface-section-head px-5 py-3">
              <h3 className="text-card-title">Checklist</h3>
            </header>
            <div>
              {record.checklist.map((entry) => (
                <div
                  key={entry.id}
                  className="flex items-center gap-3 border-b border-[var(--color-glass-hairline)] px-5 py-2.5 last:border-b-0"
                >
                  <span className="flex-none">
                    {entry.status === 'Complete' ? (
                      <CheckCircle2 size={15} strokeWidth={2.2} style={{ color: 'var(--color-success)' }} />
                    ) : (
                      <Clock size={15} strokeWidth={2.2} style={{ color: 'var(--color-warning)' }} />
                    )}
                  </span>
                  <span className="text-body min-w-0 flex-1 truncate">{entry.label}</span>
                  <span className="text-meta flex-none tabular-nums">
                    {entry.completedAt ? formatDate(entry.completedAt) : 'Pending'}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="surface-section overflow-hidden">
            <header className="surface-section-head px-5 py-3">
              <h3 className="text-card-title">Documents</h3>
            </header>
            <div>
              {record.documents.map((document) => (
                <DocumentRow
                  key={document.file}
                  name={document.name}
                  type={document.type}
                  status="Collected"
                  uploadedBy={record.generatedBy}
                  size={document.size}
                />
              ))}
            </div>
          </div>
        </div>
      </Modal>

      <Modal
        open={item !== null}
        title={item?.label ?? ''}
        description={
          item?.status === 'Complete'
            ? `Collected${item?.completedAt ? ` on ${formatDate(item.completedAt)}` : ''}`
            : 'Awaiting upload'
        }
        onClose={() => setItem(null)}
        width="560px"
        footer={
          <Button variant="secondary" className="cursor-pointer" onClick={() => setItem(null)}>
            Close
          </Button>
        }
      >
        <div className="surface-section overflow-hidden">
          {(item?.documents ?? []).map((document) => (
            <DocumentRow
              key={document.file}
              name={document.name}
              type={document.type}
              status={item?.status === 'Complete' ? 'Collected' : 'Pending'}
              uploadedBy={item?.status === 'Complete' ? record.generatedBy : undefined}
              uploadedAt={item?.completedAt ? formatDate(item.completedAt) : undefined}
              size={item?.status === 'Complete' ? document.size : undefined}
            />
          ))}
        </div>
      </Modal>
    </>
  );
}
